kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: wensleydale
  namespace: test
  labels:
    app: cheese
    cheese: wensleydale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
      task: wensleydale
  template:
    metadata:
      labels:
        app: cheese
        task: wensleydale
        version: v0.0.1
    spec:
      containers:
      - name: cheese
        image: errm/cheese:wensleydale
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wensleydale
  namespace: test
  annotations:
    kairen.example.lb/address-pool: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: cheese
    task: wensleydale