apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx-1
  name: nginx-1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-1
  template:
    metadata:
      labels:
        run: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.5
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kairen.example.lb/address-pool: default
  labels:
    run: nginx-1
  name: nginx-1
  namespace: test
spec:
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-1
  sessionAffinity: None
  type: LoadBalancer