kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cheddar
  namespace: test
  labels:
    app: cheese
    cheese: cheddar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cheese
      task: cheddar
  template:
    metadata:
      labels:
        app: cheese
        task: cheddar
        version: v0.0.1
    spec:
      containers:
      - name: cheese
        image: errm/cheese:cheddar
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cheddar
  namespace: test
  annotations:
    kairen.example.lb/address-pool: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: cheese
    task: cheddar
