apiVersion: inwinstack.com/v1
kind: Pool
metadata:
  name: test
spec:
  address: 172.22.131.200/30
  ignoreNamespaceAnnotation: true
  autoAssignToNamespace: false
  ignoreNamespaces:
  - kube-system
  - kube-public
  - default