apiVersion: v1
kind: Service
metadata:
  annotations:
    kairen.example.lb/address-pool: default
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer